coverage:
  precision: 2
  round: down
  range: '80...100'

  status:
    project: yes
    patch: yes
    changes: no

  ignore:
    - 'tests/*'
    - '**/test_*'

comment:
  layout: 'header, reach, diff, flags, files, footer'
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes

